// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMovies.Models;

namespace MyMovies.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20220202221511_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MyMovies.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            category = "Action/Adventure",
                            director = "Tom",
                            edited = false,
                            rating = "PG-13",
                            title = "Avengers, The",
                            year = (short)2012
                        },
                        new
                        {
                            ApplicationId = 2,
                            category = "Action/Adventure",
                            director = "Zach",
                            edited = false,
                            rating = "PG-13",
                            title = "Batman",
                            year = (short)1989
                        },
                        new
                        {
                            ApplicationId = 3,
                            category = "Action/Adventure",
                            director = "Jake",
                            edited = false,
                            rating = "PG-13",
                            title = "Batman & Robin",
                            year = (short)1989
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
